/**
 * Jacks or Betterment — Casino floor data
 * GENERATED by tools/fetch-casino.js. Do not edit by hand.
 * Source: vpfree2.com
 */

const CASINOS = [
  {
    "key": "peppermill-hotel-casino",
    "name": "Peppermill Hotel Casino",
    "promo": false,
    "source": "https://www.vpfree2.com/casino/peppermill-hotel-casino",
    "games": [
      {
        "name": "Deuces Wild 44",
        "variant": "NSUD",
        "ret": 99.73,
        "payouts": [
          1,
          2,
          3,
          4,
          4,
          10,
          16,
          25,
          200,
          800
        ],
        "hands": [
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "5 of a Kind",
          "Wild Royal Flush",
          "4 Deuces",
          "Natural Royal Flush"
        ],
        "denoms": [
          0.05,
          0.1,
          0.25,
          0.5
        ],
        "location": "1 Play"
      },
      {
        "name": "Double Deuces Wild",
        "variant": "DDW (FP)",
        "ret": 99.62,
        "payouts": [
          1,
          2,
          2,
          3,
          4,
          11,
          16,
          25,
          400,
          800
        ],
        "hands": [
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "5 of a Kind",
          "Wild Royal Flush",
          "4 Deuces",
          "Natural Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1
        ],
        "location": "MG"
      },
      {
        "name": "All American / USA",
        "variant": "",
        "ret": 99.6,
        "payouts": [
          1,
          1,
          3,
          8,
          8,
          8,
          35,
          200,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          1
        ],
        "location": "@ Tuscany Lounge Bar"
      },
      {
        "name": "Triple Double Bonus",
        "variant": "TDB (FP)",
        "ret": 99.58,
        "payouts": [
          1,
          1,
          2,
          4,
          7,
          9,
          50,
          80,
          160,
          400,
          800,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "4 2s–4s + A/2/3/4",
          "4 Aces + 2/3/4",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.1,
          0.25
        ],
        "location": "2 Machines"
      },
      {
        "name": "Jacks or Better",
        "variant": "JoB (FP)",
        "ret": 99.54,
        "payouts": [
          1,
          2,
          3,
          4,
          6,
          9,
          25,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.01,
          0.02,
          0.05,
          0.25
        ],
        "location": "1 Play"
      },
      {
        "name": "Double Double Bonus Aces and Faces",
        "variant": "DDBAF (FP)",
        "ret": 99.46,
        "payouts": [
          1,
          1,
          3,
          4,
          6,
          9,
          50,
          80,
          160,
          160,
          400,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "4 2s–4s + A/2/3/4",
          "4 Aces + 2/3/4",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          1
        ],
        "location": "1 Play"
      },
      {
        "name": "Bonus Aces and Faces",
        "variant": "BPAF (FP)",
        "ret": 99.26,
        "payouts": [
          1,
          2,
          3,
          4,
          5,
          8,
          25,
          40,
          80,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25
        ],
        "location": "Sports Book bar"
      },
      {
        "name": "Bonus Poker",
        "variant": "BP (FP)",
        "ret": 99.17,
        "payouts": [
          1,
          2,
          3,
          4,
          5,
          8,
          25,
          40,
          80,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.05,
          0.1,
          0.25
        ],
        "location": "MG"
      },
      {
        "name": "Big Split Poker - Jacks or Better",
        "variant": "",
        "ret": 99,
        "payouts": [
          1,
          2,
          2,
          2,
          5,
          8,
          16,
          200
        ],
        "hands": null,
        "denoms": [
          0.25,
          0.5,
          1,
          2
        ],
        "location": "1 Play"
      },
      {
        "name": "Big Split Poker - Deuces Wild",
        "variant": "",
        "ret": 98.99,
        "payouts": [
          1,
          2,
          3,
          5,
          7,
          10,
          75,
          200
        ],
        "hands": null,
        "denoms": [
          0.25,
          0.5,
          1,
          2
        ],
        "location": "1 Play"
      },
      {
        "name": "Deuces Wild 44",
        "variant": "LV Airport/Illinois Deuces",
        "ret": 98.91,
        "payouts": [
          1,
          2,
          3,
          4,
          4,
          9,
          15,
          25,
          200,
          800
        ],
        "hands": [
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "5 of a Kind",
          "Wild Royal Flush",
          "4 Deuces",
          "Natural Royal Flush"
        ],
        "denoms": [
          100
        ],
        "location": "1 Play"
      },
      {
        "name": "Big Split Poker - Joker Joker",
        "variant": "",
        "ret": 98.9,
        "payouts": [
          1,
          1,
          1,
          3,
          5,
          13,
          19,
          25,
          200
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1,
          2
        ],
        "location": "1 Play"
      },
      {
        "name": "Big Split Poker - Joker Poker",
        "variant": "",
        "ret": 98.81,
        "payouts": [
          1,
          1,
          1,
          2,
          4,
          6,
          13,
          30,
          40,
          200
        ],
        "hands": [
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "5 of a Kind",
          "Wild Royal Flush",
          "4 Deuces",
          "Natural Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1,
          2
        ],
        "location": "1 Play"
      },
      {
        "name": "Super Double Bonus",
        "variant": "",
        "ret": 98.69,
        "payouts": [
          1,
          1,
          3,
          4,
          5,
          8,
          50,
          80,
          120,
          160,
          80,
          800
        ],
        "hands": null,
        "denoms": [
          0.05,
          0.25
        ],
        "location": "at Cabaret Bar"
      },
      {
        "name": "Deuces Wild",
        "variant": "Colorado Deuces",
        "ret": 96.77,
        "payouts": [
          1,
          2,
          2,
          3,
          4,
          13,
          16,
          25,
          200,
          800
        ],
        "hands": [
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "5 of a Kind",
          "Wild Royal Flush",
          "4 Deuces",
          "Natural Royal Flush"
        ],
        "denoms": [
          0.25
        ],
        "location": "@ Qube Bar"
      }
    ]
  },
  {
    "key": "silver-legacy",
    "name": "Silver Legacy",
    "promo": true,
    "source": "https://www.vpfree2.com/casino/silver-legacy",
    "games": [
      {
        "name": "Jacks or Better",
        "variant": "JoB (FP)",
        "ret": 99.54,
        "payouts": [
          1,
          2,
          3,
          4,
          6,
          9,
          25,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1,
          2,
          5
        ],
        "location": "near escalator from Circus Circus Reno ($10 per point)"
      },
      {
        "name": "Double Double Bonus Plus",
        "variant": "",
        "ret": 99.44,
        "payouts": [
          1,
          1,
          3,
          4,
          6,
          9,
          50,
          80,
          80,
          160,
          160,
          400,
          50,
          800
        ],
        "hands": null,
        "denoms": [
          0.25,
          0.5,
          1
        ],
        "location": "MG"
      },
      {
        "name": "1 Pair (Kings or Better) Joker Wild",
        "variant": "",
        "ret": 99.29,
        "payouts": [
          1,
          1,
          2,
          3,
          5,
          7,
          18,
          50,
          100,
          200,
          940
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25
        ],
        "location": "other side of escalator to Circus Circus"
      },
      {
        "name": "Double Bonus Aces and Faces",
        "variant": "DBAF (FP)",
        "ret": 99.24,
        "payouts": [
          1,
          1,
          3,
          5,
          7,
          9,
          50,
          80,
          160,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25
        ],
        "location": "near keno"
      },
      {
        "name": "Bonus Poker",
        "variant": "BP (FP)",
        "ret": 99.17,
        "payouts": [
          1,
          2,
          3,
          4,
          5,
          8,
          25,
          40,
          80,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25
        ],
        "location": "Prog"
      },
      {
        "name": "Double Double Bonus",
        "variant": "DDB (FP)",
        "ret": 98.98,
        "payouts": [
          1,
          1,
          3,
          4,
          6,
          9,
          50,
          80,
          160,
          160,
          400,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "4 2s–4s + A/2/3/4",
          "4 Aces + 2/3/4",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25
        ],
        "location": "Prog"
      },
      {
        "name": "1 Pair (Kings or Better) Joker Wild",
        "variant": "",
        "ret": 98.94,
        "payouts": [
          1,
          1,
          2,
          3,
          5,
          7,
          18,
          50,
          100,
          200,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1
        ],
        "location": "MG"
      },
      {
        "name": "Deuces Wild 44",
        "variant": "LV Airport/Illinois Deuces",
        "ret": 98.91,
        "payouts": [
          1,
          2,
          3,
          4,
          4,
          9,
          15,
          25,
          200,
          800
        ],
        "hands": [
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "5 of a Kind",
          "Wild Royal Flush",
          "4 Deuces",
          "Natural Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1
        ],
        "location": "MG"
      },
      {
        "name": "White Hot Aces",
        "variant": "",
        "ret": 98.5,
        "payouts": [
          1,
          1,
          3,
          4,
          5,
          8,
          50,
          120,
          240,
          80,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1
        ],
        "location": "MG"
      },
      {
        "name": "All American / USA",
        "variant": "",
        "ret": 98.49,
        "payouts": [
          1,
          1,
          3,
          8,
          8,
          8,
          30,
          200,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1
        ],
        "location": "MG"
      },
      {
        "name": "Jacks or Better",
        "variant": "",
        "ret": 98.45,
        "payouts": [
          1,
          2,
          3,
          4,
          5,
          9,
          25,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.05,
          0.1
        ],
        "location": "outside high limit room"
      }
    ]
  },
  {
    "key": "eldorado-hotel-casino",
    "name": "Eldorado Reno",
    "promo": true,
    "source": "https://www.vpfree2.com/casino/eldorado-hotel-casino",
    "games": [
      {
        "name": "Deuces Wild 44",
        "variant": "NSUD",
        "ret": 99.73,
        "payouts": [
          1,
          2,
          3,
          4,
          4,
          10,
          16,
          25,
          200,
          800
        ],
        "hands": [
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "5 of a Kind",
          "Wild Royal Flush",
          "4 Deuces",
          "Natural Royal Flush"
        ],
        "denoms": [
          5,
          10
        ],
        "location": "outside high limit room ($20 per point)"
      },
      {
        "name": "Jacks or Better",
        "variant": "JoB (FP)",
        "ret": 99.54,
        "payouts": [
          1,
          2,
          3,
          4,
          6,
          9,
          25,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5
        ],
        "location": "MG"
      },
      {
        "name": "Bonus Poker",
        "variant": "BP (FP)",
        "ret": 99.17,
        "payouts": [
          1,
          2,
          3,
          4,
          5,
          8,
          25,
          40,
          80,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          1,
          2,
          5,
          10,
          25
        ],
        "location": "MG"
      },
      {
        "name": "Double Double Bonus",
        "variant": "DDB (FP)",
        "ret": 98.98,
        "payouts": [
          1,
          1,
          3,
          4,
          6,
          9,
          50,
          80,
          160,
          160,
          400,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "4 2s–4s + A/2/3/4",
          "4 Aces + 2/3/4",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          1,
          2,
          5,
          10,
          25
        ],
        "location": "MG"
      },
      {
        "name": "Deuces Wild 44",
        "variant": "LV Airport/Illinois Deuces",
        "ret": 98.91,
        "payouts": [
          1,
          2,
          3,
          4,
          4,
          9,
          15,
          25,
          200,
          800
        ],
        "hands": [
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "5 of a Kind",
          "Wild Royal Flush",
          "4 Deuces",
          "Natural Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5
        ],
        "location": "MG"
      }
    ]
  }
];
