/**
 * Jacks or Bettorment — Casino floor data
 * GENERATED by tools/fetch-casino.js. Do not edit by hand.
 * Source: vpfree2.com
 */

const CASINOS = [
  {
    "key": "silver-legacy",
    "name": "Silver Legacy",
    "promo": true,
    "source": "https://www.vpfree2.com/casino/silver-legacy",
    "games": [
      {
        "name": "Jacks or Better",
        "variant": "JoB (FP)",
        "ret": 99.54,
        "payouts": [
          1,
          2,
          3,
          4,
          6,
          9,
          25,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1,
          2,
          5
        ],
        "banks": [
          {
            "denoms": [
              0.25,
              0.5,
              1,
              2,
              5
            ],
            "perPoint": 10,
            "location": "near escalator from Circus Circus Reno ($10 per point)",
            "play": "1 Play",
            "machines": "3 Machines"
          }
        ]
      },
      {
        "name": "Double Double Bonus Plus",
        "variant": "",
        "ret": 99.44,
        "payouts": [
          1,
          1,
          3,
          4,
          6,
          9,
          50,
          80,
          80,
          160,
          160,
          400,
          50,
          800
        ],
        "hands": null,
        "denoms": [
          0.25,
          0.5,
          1
        ],
        "banks": [
          {
            "denoms": [
              0.25,
              0.5,
              1
            ],
            "perPoint": null,
            "location": "just outside poker room (with prog. meter on top)",
            "play": "1 Play",
            "machines": "1 Machine"
          },
          {
            "denoms": [
              1
            ],
            "perPoint": null,
            "location": "several throughout",
            "play": "1 Play",
            "machines": ""
          }
        ]
      },
      {
        "name": "1 Pair (Kings or Better) Joker Wild",
        "variant": "",
        "ret": 99.29,
        "payouts": [
          1,
          1,
          2,
          3,
          5,
          7,
          18,
          50,
          100,
          200,
          940
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1
        ],
        "banks": [
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "other side of escalator to Circus Circus",
            "play": "3 Play",
            "machines": "10 Slant-tops"
          },
          {
            "denoms": [
              0.25,
              0.5,
              1
            ],
            "perPoint": null,
            "location": "near keno",
            "play": "5-50 Coins",
            "machines": "4 Slant-tops"
          }
        ]
      },
      {
        "name": "Double Bonus Aces and Faces",
        "variant": "DBAF (FP)",
        "ret": 99.24,
        "payouts": [
          1,
          1,
          3,
          5,
          7,
          9,
          50,
          80,
          160,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25
        ],
        "banks": [
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "near keno",
            "play": "1 Play",
            "machines": "4 Slant-tops"
          }
        ]
      },
      {
        "name": "Bonus Poker",
        "variant": "BP (FP)",
        "ret": 99.17,
        "payouts": [
          1,
          2,
          3,
          4,
          5,
          8,
          25,
          40,
          80,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1
        ],
        "banks": [
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "near keno",
            "play": "1 Play",
            "machines": "1 Slant-top"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "near Drinx Bar",
            "play": "1 Play",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              0.25,
              0.5,
              1
            ],
            "perPoint": null,
            "location": "several banks",
            "play": "1 Play",
            "machines": ""
          },
          {
            "denoms": [
              0.25,
              0.5,
              1
            ],
            "perPoint": null,
            "location": "just outside poker room (with prog. meter on top)",
            "play": "1 Play",
            "machines": "1 Machine"
          }
        ]
      },
      {
        "name": "Double Double Bonus",
        "variant": "DDB (FP)",
        "ret": 98.98,
        "payouts": [
          1,
          1,
          3,
          4,
          6,
          9,
          50,
          80,
          160,
          160,
          400,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "4 2s–4s + A/2/3/4",
          "4 Aces + 2/3/4",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1,
          2
        ],
        "banks": [
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "in the corner near Virginia & 5th streets",
            "play": "1 Play",
            "machines": "4 Uprights"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "near keno",
            "play": "1 Play",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "near south escalator men&#39;s room",
            "play": "1 Play",
            "machines": "8 Slant-tops"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "just west of north escalator",
            "play": "1 Play",
            "machines": "6 Slant-tops"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "in SW corner",
            "play": "1 Play",
            "machines": "5 Uprights ("
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "along south wall in SW quadrant of main casino floor",
            "play": "1 Play",
            "machines": "12 Uprights"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "in NW corner of casino",
            "play": "1 Play",
            "machines": "10 Slant-tops"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "just outside poker room (with prog. meter on top)",
            "play": "1 Play",
            "machines": "1 Machine"
          },
          {
            "denoms": [
              0.25,
              0.5
            ],
            "perPoint": null,
            "location": "just outside poker room (with prog. meter on top)",
            "play": "1 Play",
            "machines": "1 Machine"
          },
          {
            "denoms": [
              0.25,
              0.5,
              1
            ],
            "perPoint": null,
            "location": "several banks",
            "play": "1 Play",
            "machines": ""
          },
          {
            "denoms": [
              0.25,
              0.5,
              1,
              2
            ],
            "perPoint": null,
            "location": "near buffet",
            "play": "",
            "machines": "4 Slant-tops"
          },
          {
            "denoms": [
              1
            ],
            "perPoint": null,
            "location": "in two banks near center bar on main floor",
            "play": "1 Play",
            "machines": "20 Slant-tops"
          }
        ]
      },
      {
        "name": "1 Pair (Kings or Better) Joker Wild",
        "variant": "",
        "ret": 98.94,
        "payouts": [
          1,
          1,
          2,
          3,
          5,
          7,
          18,
          50,
          100,
          200,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1
        ],
        "banks": [
          {
            "denoms": [
              0.25,
              0.5,
              1
            ],
            "perPoint": null,
            "location": "just outside poker room (with prog. meter on top)",
            "play": "1 Play",
            "machines": "1 Machine"
          }
        ]
      },
      {
        "name": "Deuces Wild 44",
        "variant": "LV Airport/Illinois Deuces",
        "ret": 98.91,
        "payouts": [
          1,
          2,
          3,
          4,
          4,
          9,
          15,
          25,
          200,
          800
        ],
        "hands": [
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "5 of a Kind",
          "Wild Royal Flush",
          "4 Deuces",
          "Natural Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1
        ],
        "banks": [
          {
            "denoms": [
              0.25,
              0.5,
              1
            ],
            "perPoint": null,
            "location": "just outside poker room (with prog. meter on top)",
            "play": "1 Play",
            "machines": "1 Machine"
          }
        ]
      },
      {
        "name": "White Hot Aces",
        "variant": "",
        "ret": 98.5,
        "payouts": [
          1,
          1,
          3,
          4,
          5,
          8,
          50,
          120,
          240,
          80,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1
        ],
        "banks": [
          {
            "denoms": [
              0.25,
              0.5,
              1
            ],
            "perPoint": null,
            "location": "just outside poker room (with prog. meter on top)",
            "play": "1 Play",
            "machines": "1 Machine"
          }
        ]
      },
      {
        "name": "All American / USA",
        "variant": "",
        "ret": 98.49,
        "payouts": [
          1,
          1,
          3,
          8,
          8,
          8,
          30,
          200,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1
        ],
        "banks": [
          {
            "denoms": [
              0.25,
              0.5,
              1
            ],
            "perPoint": null,
            "location": "just outside poker room (with prog. meter on top)",
            "play": "1 Play",
            "machines": "1 Machine"
          }
        ]
      },
      {
        "name": "Jacks or Better",
        "variant": "",
        "ret": 98.45,
        "payouts": [
          1,
          2,
          3,
          4,
          5,
          9,
          25,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.05,
          0.1,
          0.25
        ],
        "banks": [
          {
            "denoms": [
              0.05,
              0.1
            ],
            "perPoint": null,
            "location": "outside high limit room",
            "play": "100 Play",
            "machines": "1 Slant-top"
          },
          {
            "denoms": [
              0.05,
              0.1,
              0.25
            ],
            "perPoint": null,
            "location": "outside high limit room",
            "play": "50 Play",
            "machines": "1 Slant-top"
          }
        ]
      }
    ]
  },
  {
    "key": "eldorado-hotel-casino",
    "name": "Eldorado Reno",
    "promo": true,
    "source": "https://www.vpfree2.com/casino/eldorado-hotel-casino",
    "games": [
      {
        "name": "Deuces Wild 44",
        "variant": "NSUD",
        "ret": 99.73,
        "payouts": [
          1,
          2,
          3,
          4,
          4,
          10,
          16,
          25,
          200,
          800
        ],
        "hands": [
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "5 of a Kind",
          "Wild Royal Flush",
          "4 Deuces",
          "Natural Royal Flush"
        ],
        "denoms": [
          5,
          10
        ],
        "banks": [
          {
            "denoms": [
              5,
              10
            ],
            "perPoint": 20,
            "location": "outside high limit room ($20 per point)",
            "play": "1 Play",
            "machines": "2 Slant-tops"
          }
        ]
      },
      {
        "name": "Jacks or Better",
        "variant": "JoB (FP)",
        "ret": 99.54,
        "payouts": [
          1,
          2,
          3,
          4,
          6,
          9,
          25,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1,
          2,
          5,
          10,
          25
        ],
        "banks": [
          {
            "denoms": [
              0.25,
              0.5
            ],
            "perPoint": 20,
            "location": "outside high limit room ($20 per point)",
            "play": "100 Play",
            "machines": "1 Slant-top"
          },
          {
            "denoms": [
              0.25,
              0.5,
              1
            ],
            "perPoint": 10,
            "location": "near 4th/Virginia entrance ($10 per point)",
            "play": "1 Play",
            "machines": "5 Machines"
          },
          {
            "denoms": [
              2,
              5,
              10,
              25
            ],
            "perPoint": null,
            "location": "several single-line and/or multiline banks throughout",
            "play": "1 Play",
            "machines": ""
          },
          {
            "denoms": [
              5
            ],
            "perPoint": null,
            "location": "in the Gold Room",
            "play": "1 Play",
            "machines": ""
          }
        ]
      },
      {
        "name": "Bonus Poker",
        "variant": "BP (FP)",
        "ret": 99.17,
        "payouts": [
          1,
          2,
          3,
          4,
          5,
          8,
          25,
          40,
          80,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          1,
          2,
          5,
          10,
          25
        ],
        "banks": [
          {
            "denoms": [
              1,
              2,
              5,
              10,
              25
            ],
            "perPoint": null,
            "location": "several single-line and/or multiline banks throughout",
            "play": "1 Play",
            "machines": ""
          },
          {
            "denoms": [
              5,
              10,
              25
            ],
            "perPoint": null,
            "location": "high limit room (3) bartops and (4) uprights",
            "play": "1 Play",
            "machines": "7 Machines"
          }
        ]
      },
      {
        "name": "Double Double Bonus",
        "variant": "DDB (FP)",
        "ret": 98.98,
        "payouts": [
          1,
          1,
          3,
          4,
          6,
          9,
          50,
          80,
          160,
          160,
          400,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "4 2s–4s + A/2/3/4",
          "4 Aces + 2/3/4",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          1,
          2,
          5,
          10,
          25
        ],
        "banks": [
          {
            "denoms": [
              1,
              2,
              5,
              10,
              25
            ],
            "perPoint": null,
            "location": "several single-line and/or multiline banks throughout",
            "play": "1 Play",
            "machines": ""
          },
          {
            "denoms": [
              5,
              10,
              25
            ],
            "perPoint": null,
            "location": "high limit room (3) bartops and (4) uprights",
            "play": "1 Play",
            "machines": "7 Machines"
          }
        ]
      },
      {
        "name": "Deuces Wild 44",
        "variant": "LV Airport/Illinois Deuces",
        "ret": 98.91,
        "payouts": [
          1,
          2,
          3,
          4,
          4,
          9,
          15,
          25,
          200,
          800
        ],
        "hands": [
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "5 of a Kind",
          "Wild Royal Flush",
          "4 Deuces",
          "Natural Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1,
          2,
          5,
          10,
          25
        ],
        "banks": [
          {
            "denoms": [
              0.25,
              0.5
            ],
            "perPoint": 20,
            "location": "outside high limit room ($20 per point)",
            "play": "100 Play",
            "machines": "1 Slant-top"
          },
          {
            "denoms": [
              1,
              2,
              5,
              10,
              25
            ],
            "perPoint": null,
            "location": "high limit room (3) bartops and (4) uprights",
            "play": "1 Play",
            "machines": "7 Machines"
          },
          {
            "denoms": [
              1,
              2,
              5,
              10,
              25
            ],
            "perPoint": null,
            "location": "several single-line and/or multiline banks throughout",
            "play": "1 Play",
            "machines": ""
          }
        ]
      }
    ]
  },
  {
    "key": "peppermill-hotel-casino",
    "name": "Peppermill Hotel Casino",
    "promo": false,
    "source": "https://www.vpfree2.com/casino/peppermill-hotel-casino",
    "games": [
      {
        "name": "Deuces Wild 44",
        "variant": "NSUD",
        "ret": 99.73,
        "payouts": [
          1,
          2,
          3,
          4,
          4,
          10,
          16,
          25,
          200,
          800
        ],
        "hands": [
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "5 of a Kind",
          "Wild Royal Flush",
          "4 Deuces",
          "Natural Royal Flush"
        ],
        "denoms": [
          0.05,
          0.1,
          0.25,
          0.5,
          1,
          2,
          5
        ],
        "banks": [
          {
            "denoms": [
              0.05,
              0.1,
              0.25,
              0.5
            ],
            "perPoint": null,
            "location": "in front of Romanza",
            "play": "5-10 Coins",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              0.05,
              0.1,
              0.25,
              0.5
            ],
            "perPoint": null,
            "location": "near Dino Dollars.",
            "play": "5-10 Coins",
            "machines": "3 Uprights"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "near the Fireside Lounge and The Pub",
            "play": "1 Play",
            "machines": "8 Slant-tops"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "on right near the semi-circular exit doors, between the bar with the giant screen and Oceano",
            "play": "1 Play",
            "machines": "6 Slant-tops"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "on left near the semi-circular exit doors, between the bar with the giant screen and Oceano",
            "play": "1-3 Coins",
            "machines": "5 Slant-tops"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "between the buffet and the Coffee Shop",
            "play": "5 Play",
            "machines": "1 Slant-top"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "between the slot club desk and Chi",
            "play": "50 Play",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "on the wall across from the slot club ($1199 royal)",
            "play": "1 Play",
            "machines": ""
          },
          {
            "denoms": [
              0.25,
              1
            ],
            "perPoint": null,
            "location": "and uprights scattered around casino",
            "play": "",
            "machines": ""
          },
          {
            "denoms": [
              0.25,
              1
            ],
            "perPoint": null,
            "location": "just north of Buffet cashier",
            "play": "10 Play",
            "machines": "6 Uprights"
          },
          {
            "denoms": [
              0.25,
              0.5,
              1
            ],
            "perPoint": null,
            "location": "near Romanza",
            "play": "5-10 Coins",
            "machines": "4 Slant-tops"
          },
          {
            "denoms": [
              1
            ],
            "perPoint": null,
            "location": "in the Dino slots area against the wall",
            "play": "1 Play",
            "machines": ""
          },
          {
            "denoms": [
              1
            ],
            "perPoint": null,
            "location": "in the high-limit area",
            "play": "5-10 Coins",
            "machines": "1 Slant-top"
          },
          {
            "denoms": [
              1
            ],
            "perPoint": null,
            "location": "in the high-limit area",
            "play": "5-15 Coins",
            "machines": "5 Slant-tops"
          },
          {
            "denoms": [
              1,
              2,
              5
            ],
            "perPoint": null,
            "location": "in High Limit Slots area",
            "play": "1 Play",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              5
            ],
            "perPoint": null,
            "location": "in the high-limit area",
            "play": "1 Play",
            "machines": "4 Uprights"
          }
        ]
      },
      {
        "name": "Double Deuces Wild",
        "variant": "DDW (FP)",
        "ret": 99.62,
        "payouts": [
          1,
          2,
          2,
          3,
          4,
          11,
          16,
          25,
          400,
          800
        ],
        "hands": [
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "5 of a Kind",
          "Wild Royal Flush",
          "4 Deuces",
          "Natural Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1
        ],
        "banks": [
          {
            "denoms": [
              0.25,
              0.5,
              1
            ],
            "perPoint": null,
            "location": "near the Fireside Lounge and The Pub",
            "play": "1 Play",
            "machines": "8 Slant-tops"
          }
        ]
      },
      {
        "name": "All American / USA",
        "variant": "",
        "ret": 99.6,
        "payouts": [
          1,
          1,
          3,
          8,
          8,
          8,
          35,
          200,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          1
        ],
        "banks": [
          {
            "denoms": [
              0.25,
              1
            ],
            "perPoint": null,
            "location": "@ Tuscany Lounge Bar",
            "play": "1 Play",
            "machines": ""
          }
        ]
      },
      {
        "name": "Triple Double Bonus",
        "variant": "TDB (FP)",
        "ret": 99.58,
        "payouts": [
          1,
          1,
          2,
          4,
          7,
          9,
          50,
          80,
          160,
          400,
          800,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "4 2s–4s + A/2/3/4",
          "4 Aces + 2/3/4",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.1,
          0.25,
          0.5,
          1
        ],
        "banks": [
          {
            "denoms": [
              0.1,
              0.25
            ],
            "perPoint": null,
            "location": "",
            "play": "50 Play",
            "machines": "2 Machines"
          },
          {
            "denoms": [
              0.25,
              0.5,
              1
            ],
            "perPoint": null,
            "location": "by the blue keno lounge near the Steak House",
            "play": "1 Play",
            "machines": "6 Slant-tops"
          },
          {
            "denoms": [
              0.25,
              0.5,
              1
            ],
            "perPoint": null,
            "location": "near the Fireside Lounge and The Pub",
            "play": "1 Play",
            "machines": "8 Slant-tops"
          }
        ]
      },
      {
        "name": "Jacks or Better",
        "variant": "JoB (FP)",
        "ret": 99.54,
        "payouts": [
          1,
          2,
          3,
          4,
          6,
          9,
          25,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.01,
          0.02,
          0.05,
          0.1,
          0.2,
          0.25,
          0.5,
          1,
          2,
          5,
          10,
          25,
          100
        ],
        "banks": [
          {
            "denoms": [
              0.01,
              0.02,
              0.05,
              0.25
            ],
            "perPoint": null,
            "location": "in the hallway outside the coffee shop",
            "play": "5-25 Coins",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              0.05,
              0.1,
              0.25
            ],
            "perPoint": null,
            "location": "near the change booth by the slot club.",
            "play": "50 Play",
            "machines": "1 Slant-top"
          },
          {
            "denoms": [
              0.05,
              0.25,
              1
            ],
            "perPoint": null,
            "location": "in the tunnel by the coffee shop.",
            "play": "5-10 Coins",
            "machines": "1 Upright"
          },
          {
            "denoms": [
              0.05,
              0.1,
              0.25,
              0.5
            ],
            "perPoint": null,
            "location": "in front of Romanza",
            "play": "5-10 Coins",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              0.05,
              0.1,
              0.25,
              0.5
            ],
            "perPoint": null,
            "location": "near Dino Dollars.",
            "play": "5-10 Coins",
            "machines": "3 Uprights"
          },
          {
            "denoms": [
              0.1,
              0.2,
              0.25
            ],
            "perPoint": null,
            "location": "just outside the Sportsbook",
            "play": "50 Play",
            "machines": "1 Upright"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "between the slot club desk and Chi",
            "play": "50 Play",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "and slant-tops scattered around casino",
            "play": "",
            "machines": ""
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "between Oceano and the poker room",
            "play": "5 Play",
            "machines": "1 Slant-top"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "on the wall across from the slot club ($1199 royal)",
            "play": "1 Play",
            "machines": ""
          },
          {
            "denoms": [
              0.25,
              0.5
            ],
            "perPoint": null,
            "location": "(2) between Chi and the bathrooms; (1) in non-smoking area near Cafe Milano",
            "play": "",
            "machines": "3 Slant-tops"
          },
          {
            "denoms": [
              0.25,
              1
            ],
            "perPoint": null,
            "location": "@ Qube Bar",
            "play": "1 Play",
            "machines": ""
          },
          {
            "denoms": [
              0.25,
              1
            ],
            "perPoint": null,
            "location": "between buffet and coffee shop",
            "play": "1 Play",
            "machines": "5 Slant-tops"
          },
          {
            "denoms": [
              0.25,
              1
            ],
            "perPoint": null,
            "location": "just north of Buffet cashier",
            "play": "10 Play",
            "machines": "6 Uprights"
          },
          {
            "denoms": [
              0.25,
              0.5,
              1
            ],
            "perPoint": null,
            "location": "near Romanza",
            "play": "5-10 Coins",
            "machines": "4 Slant-tops"
          },
          {
            "denoms": [
              1
            ],
            "perPoint": null,
            "location": "near secondary cashier near hotel tower elevators",
            "play": "1 Play",
            "machines": ""
          },
          {
            "denoms": [
              1,
              2,
              5
            ],
            "perPoint": null,
            "location": "in High Limit Slots area",
            "play": "1 Play",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              1,
              2,
              5,
              10
            ],
            "perPoint": null,
            "location": "in the High Limit Slots area",
            "play": "",
            "machines": ""
          },
          {
            "denoms": [
              1,
              2,
              5,
              10,
              25
            ],
            "perPoint": null,
            "location": "in the the high-limit area",
            "play": "1 Play",
            "machines": ""
          },
          {
            "denoms": [
              5
            ],
            "perPoint": null,
            "location": "@ the high-limit bar",
            "play": "1 Play",
            "machines": ""
          },
          {
            "denoms": [
              5,
              10,
              25
            ],
            "perPoint": null,
            "location": "in the High Limit Slots area",
            "play": "",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              100
            ],
            "perPoint": null,
            "location": "in the High Limit Slots area",
            "play": "3 Coins",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              100
            ],
            "perPoint": null,
            "location": "in the High Limit Slots area",
            "play": "3 Coins",
            "machines": "1 Upright"
          }
        ]
      },
      {
        "name": "Double Double Bonus Aces and Faces",
        "variant": "DDBAF (FP)",
        "ret": 99.46,
        "payouts": [
          1,
          1,
          3,
          4,
          6,
          9,
          50,
          80,
          160,
          160,
          400,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "4 2s–4s + A/2/3/4",
          "4 Aces + 2/3/4",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          1
        ],
        "banks": [
          {
            "denoms": [
              0.25,
              1
            ],
            "perPoint": null,
            "location": "",
            "play": "5-25 Coins",
            "machines": ""
          }
        ]
      },
      {
        "name": "Bonus Aces and Faces",
        "variant": "BPAF (FP)",
        "ret": 99.26,
        "payouts": [
          1,
          2,
          3,
          4,
          5,
          8,
          25,
          40,
          80,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25
        ],
        "banks": [
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "Sports Book bar",
            "play": "1 Play",
            "machines": ""
          }
        ]
      },
      {
        "name": "Bonus Poker",
        "variant": "BP (FP)",
        "ret": 99.17,
        "payouts": [
          1,
          2,
          3,
          4,
          5,
          8,
          25,
          40,
          80,
          50,
          800
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 5s–Ks",
          "4 2s–4s",
          "4 Aces",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.05,
          0.1,
          0.2,
          0.25,
          0.5,
          1,
          2,
          5,
          10,
          25,
          100
        ],
        "banks": [
          {
            "denoms": [
              0.05,
              0.1,
              0.25
            ],
            "perPoint": null,
            "location": "near the change booth by the slot club.",
            "play": "50 Play",
            "machines": "1 Slant-top"
          },
          {
            "denoms": [
              0.05,
              0.25,
              1
            ],
            "perPoint": null,
            "location": "in the tunnel by the coffee shop.",
            "play": "5-10 Coins",
            "machines": "1 Upright"
          },
          {
            "denoms": [
              0.05,
              0.1,
              0.25,
              0.5
            ],
            "perPoint": null,
            "location": "in front of Romanza",
            "play": "5-10 Coins",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              0.05,
              0.1,
              0.25,
              0.5
            ],
            "perPoint": null,
            "location": "near Dino Dollars.",
            "play": "5-10 Coins",
            "machines": "3 Uprights"
          },
          {
            "denoms": [
              0.1,
              0.2,
              0.25
            ],
            "perPoint": null,
            "location": "just outside the Sportsbook",
            "play": "50 Play",
            "machines": "1 Upright"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "between the slot club desk and Chi",
            "play": "50 Play",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "between Oceano and the poker room",
            "play": "5 Play",
            "machines": "1 Slant-top"
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "bank near the Fireside Lounge and The Pub",
            "play": "1 Play",
            "machines": ""
          },
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "in front of the slot club, one row back.",
            "play": "50 Play",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              1,
              2,
              5
            ],
            "perPoint": null,
            "location": "in High Limit Slots area",
            "play": "1 Play",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              5,
              10,
              25
            ],
            "perPoint": null,
            "location": "in the High Limit Slots area",
            "play": "",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              100
            ],
            "perPoint": null,
            "location": "in the High Limit Slots area",
            "play": "3 Coins",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              100
            ],
            "perPoint": null,
            "location": "in the High Limit Slots area",
            "play": "3 Coins",
            "machines": "1 Upright"
          }
        ]
      },
      {
        "name": "Big Split Poker - Jacks or Better",
        "variant": "",
        "ret": 99,
        "payouts": [
          1,
          2,
          2,
          2,
          5,
          8,
          16,
          200
        ],
        "hands": null,
        "denoms": [
          0.25,
          0.5,
          1,
          2
        ],
        "banks": [
          {
            "denoms": [
              0.25,
              0.5,
              1,
              2
            ],
            "perPoint": null,
            "location": "just inside the high-limit slot area",
            "play": "10-40 Coins",
            "machines": "3 Slant-tops"
          }
        ]
      },
      {
        "name": "Big Split Poker - Deuces Wild",
        "variant": "",
        "ret": 98.99,
        "payouts": [
          1,
          2,
          3,
          5,
          7,
          10,
          75,
          200
        ],
        "hands": null,
        "denoms": [
          0.25,
          0.5,
          1,
          2
        ],
        "banks": [
          {
            "denoms": [
              0.25,
              0.5,
              1,
              2
            ],
            "perPoint": null,
            "location": "just inside the high-limit slot area",
            "play": "10-40 Coins",
            "machines": "3 Slant-tops"
          }
        ]
      },
      {
        "name": "Deuces Wild 44",
        "variant": "LV Airport/Illinois Deuces",
        "ret": 98.91,
        "payouts": [
          1,
          2,
          3,
          4,
          4,
          9,
          15,
          25,
          200,
          800
        ],
        "hands": [
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "5 of a Kind",
          "Wild Royal Flush",
          "4 Deuces",
          "Natural Royal Flush"
        ],
        "denoms": [
          100
        ],
        "banks": [
          {
            "denoms": [
              100
            ],
            "perPoint": null,
            "location": "in the High Limit Slots area",
            "play": "3 Coins",
            "machines": ""
          }
        ]
      },
      {
        "name": "Big Split Poker - Joker Joker",
        "variant": "",
        "ret": 98.9,
        "payouts": [
          1,
          1,
          1,
          3,
          5,
          13,
          19,
          25,
          200
        ],
        "hands": [
          "Jacks or Better",
          "Two Pair",
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1,
          2
        ],
        "banks": [
          {
            "denoms": [
              0.25,
              0.5,
              1,
              2
            ],
            "perPoint": null,
            "location": "just inside the high-limit slot area",
            "play": "10-40 Coins",
            "machines": "3 Slant-tops"
          }
        ]
      },
      {
        "name": "Big Split Poker - Joker Poker",
        "variant": "",
        "ret": 98.81,
        "payouts": [
          1,
          1,
          1,
          2,
          4,
          6,
          13,
          30,
          40,
          200
        ],
        "hands": [
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "5 of a Kind",
          "Wild Royal Flush",
          "4 Deuces",
          "Natural Royal Flush"
        ],
        "denoms": [
          0.25,
          0.5,
          1,
          2
        ],
        "banks": [
          {
            "denoms": [
              0.25,
              0.5,
              1,
              2
            ],
            "perPoint": null,
            "location": "just inside the high-limit slot area",
            "play": "10-40 Coins",
            "machines": "3 Slant-tops"
          }
        ]
      },
      {
        "name": "Super Double Bonus",
        "variant": "",
        "ret": 98.69,
        "payouts": [
          1,
          1,
          3,
          4,
          5,
          8,
          50,
          80,
          120,
          160,
          80,
          800
        ],
        "hands": null,
        "denoms": [
          0.05,
          0.25
        ],
        "banks": [
          {
            "denoms": [
              0.05,
              0.25
            ],
            "perPoint": null,
            "location": "at Cabaret Bar",
            "play": "50 Play",
            "machines": "4 Slant-tops"
          },
          {
            "denoms": [
              0.05,
              0.25
            ],
            "perPoint": null,
            "location": "between coffee shop and restrooms",
            "play": "50 Play",
            "machines": "2 Slant-tops"
          },
          {
            "denoms": [
              0.05,
              0.25
            ],
            "perPoint": null,
            "location": "near the Qube Bar",
            "play": "100 Play",
            "machines": "1 Slant-top"
          }
        ]
      },
      {
        "name": "Deuces Wild",
        "variant": "Colorado Deuces",
        "ret": 96.77,
        "payouts": [
          1,
          2,
          2,
          3,
          4,
          13,
          16,
          25,
          200,
          800
        ],
        "hands": [
          "3 of a Kind",
          "Straight",
          "Flush",
          "Full House",
          "4 of a Kind",
          "Straight Flush",
          "5 of a Kind",
          "Wild Royal Flush",
          "4 Deuces",
          "Natural Royal Flush"
        ],
        "denoms": [
          0.25
        ],
        "banks": [
          {
            "denoms": [
              0.25
            ],
            "perPoint": null,
            "location": "@ Qube Bar",
            "play": "1 Play",
            "machines": ""
          }
        ]
      }
    ]
  }
];
